#!/bin/bash

display=":$(ls /tmp/.X11-unix/* | sed 's#/tmp/.X11-unix/X##' | head -n 1)"
user=$(who | grep '('$display')' | awk '{print $1}' | head -n 1)
uid=$(id -u $user)
su "$user" -c "DISPLAY=:$display DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$uid/bus notify-send 'netctl' 'Profile stopped' -t 4000 -i network-wireless"
